ALTER TABLE `SALESPERSONROLE` ADD COLUMN `AGENT_MB` tinyint(1) NULL DEFAULT '0' AFTER `AGENT_SA`;
ALTER TABLE `SALESPERSONROLE` ADD COLUMN `AGENT_LB` tinyint(1) NULL DEFAULT '0' AFTER `AGENT_MB`; 
ALTER TABLE `SALESPERSONROLE` ADD COLUMN `DIVISION` varchar(30) NULL AFTER `AGENT_LB`; 
ALTER TABLE `campaign` ADD COLUMN `FILTERTEXT` varchar(100) NULL AFTER `PRODUCTTEXT`; 
UPDATE `businessarea` set `CUMULATIVEDISCOUNTS` = 1 WHERE `NAME`= 'TDC Erhverv Omstilling';
DELETE FROM `productrelation` WHERE `ID` IN (19497, 19498, 19499);
ALTER TABLE `product` ADD COLUMN `SUBSCRIBERPRODUCT` tinyint(1) NULL DEFAULT '0' AFTER `TDCINSTALLATION`;
DELETE FROM `orderline` WHERE `PRODUCT_ID` = 19487;
DELETE FROM `product` WHERE `ID` = 19487;
