package dk.jyskit.waf.wicket.components.forms.jsr303form.components.textfield;

import java.util.Map;

import org.apache.wicket.markup.html.form.TextField;

import dk.jyskit.waf.wicket.components.forms.jsr303form.ComponentContainerPanel;
import dk.jyskit.waf.wicket.components.forms.jsr303form.components.ComponentWithLabelAndValidationPanel;

public class TextFieldPanel extends ComponentWithLabelAndValidationPanel<TextField> {
	public TextFieldPanel(ComponentContainerPanel container, final String fieldName, Map<String, String> attributesMap) {
		super(container, fieldName);
		init(new TextField("editor", propertyModel) {
			@Override
			public String getInputName() {
				return fieldName;  // To avoid a random name generated by Wicket
			}
		}, attributesMap);
	}
}

