package dk.jyskit.salescloud.application.pages.partner;

import java.util.HashMap;

import org.apache.wicket.markup.html.form.FormComponent;

import dk.jyskit.waf.wicket.components.forms.jsr303form.ComponentContainerPanel;
import dk.jyskit.waf.wicket.components.forms.jsr303form.components.ComponentWithLabelAndValidationPanel;

public class ProductPriceAndCountRowPanel extends ComponentWithLabelAndValidationPanel<FormComponent<Object>> {

	public ProductPriceAndCountRowPanel(ComponentContainerPanel container, final String fieldName) {
		super(container, fieldName);
		init(new ProductPriceAndCountRowEditor("editor", propertyModel) {
			@Override
			public String getInputName() {
				return fieldName;  // To avoid a random name generated by Wicket
			}
		}, new HashMap<String, String>());
	}

	public ProductPriceAndCountRowPanel(ComponentContainerPanel container, final String fieldName, boolean showName) {
		super(container, fieldName);
		init(new ProductPriceAndCountRowEditor("editor", propertyModel, showName, false) {
			@Override
			public String getInputName() {
				return fieldName;  // To avoid a random name generated by Wicket
			}
		}, new HashMap<String, String>());
	}

	public ProductPriceAndCountRowPanel(ComponentContainerPanel container, final String fieldName, boolean showName, boolean readonlyPrice) {
		super(container, fieldName);
		init(new ProductPriceAndCountRowEditor("editor", propertyModel, showName, readonlyPrice) {
			@Override
			public String getInputName() {
				return fieldName;  // To avoid a random name generated by Wicket
			}
		}, new HashMap<String, String>());
	}
}
